name: translator-api
region: tor
services:
  - name: translator-web
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 3000
    source_dir: /
    build_command: npx prisma generate && npm run build
    run_command: npm start
        envs:
          - key: REDIS_URL
            scope: RUN_TIME
            type: SECRET
          - key: DATABASE_URL
            scope: RUN_TIME
            type: SECRET
          - key: DEEPL_AUTH_KEY
            scope: RUN_TIME
            type: SECRET
                - key: AI_API_KEY
                  scope: RUN_TIME
                  type: SECRET
                - key: GOOGLE_CLIENT_ID
                  scope: RUN_TIME
                  type: SECRET
                - key: GOOGLE_CLIENT_SECRET
                  scope: RUN_TIME
                  type: SECRET
                - key: SESSION_SECRET
                  scope: RUN_TIME
                  type: SECRET
                - key: BASE_URL
                  scope: RUN_TIME
            - name: translator-worker
          
        instance_count: 1
        instance_size_slug: basic-xxs
        source_dir: /
        build_command: npx prisma generate && npm run build
        run_command: node dist/worker.js
        envs:
          - key: REDIS_URL
            scope: RUN_TIME
            type: SECRET
          - key: DATABASE_URL
            scope: RUN_TIME
            type: SECRET
          - key: DEEPL_AUTH_KEY
            scope: RUN_TIME
            type: SECRET
          - key: AI_API_KEY
            scope: RUN_TIME
            type: SECRET
    